[package]
name = "autopush_common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "autopush_common"

[dependencies]
actix-web.workspace = true
actix-http.workspace = true
backtrace.workspace = true
base64.workspace = true
cadence.workspace = true
chrono.workspace = true
config.workspace = true
fernet.workspace = true
futures.workspace = true
futures-util.workspace = true
hex.workspace = true
httparse.workspace = true
hyper.workspace = true
lazy_static.workspace = true
log.workspace = true
openssl.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
rusoto_core.workspace = true
rusoto_credential.workspace = true
rusoto_dynamodb.workspace = true
sentry-backtrace.workspace = true
sentry.workspace = true
sentry-core.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_dynamodb.workspace = true
serde_json.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-envlogger.workspace = true
slog-mozlog-json.workspace = true
slog-scope.workspace = true
slog-stdlog.workspace = true
slog-term.workspace = true
tokio.workspace = true
tokio-core.workspace = true
# tokio-postgres.workspace = true
thiserror.workspace = true
tungstenite.workspace = true
uuid.workspace = true
url.workspace = true

again = "0.1"
async-trait = "0.1"
futures-backoff = "0.1.0"
mozsvc-common = "0.2"
woothee = "0.13"
mockall = "0.8.3"  # 0.9+ requires reworking tests

[dev-dependencies]
mockito = "0.31"
tempfile = "3.2.0"
tokio = { version = "1.26", features = ["macros"] }
