[workspace]
members = [
    "autopush-common",
    "autopush",
    "autoendpoint",
    "autoconnect",
    "autoconnect/autoconnect-common",
    "autoconnect/autoconnect-settings",
    "autoconnect/autoconnect-web",
    "autoconnect/autoconnect-ws",
    "autoconnect/autoconnect-ws/autoconnect-ws-clientsm",
]

[workspace.package]
version = "1.66.0"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Mark Drobnak <mdrobnak@mozilla.com>",
]
edition = "2021"

[workspace.dependencies]
# ideally, this would contain any crates that are shared between crates.
# there are some lingering code interdependencies that prevent that, but it should
# remain a goal for the overall refactor.
actix = "0.13"
actix-cors = "0.6"
actix-http = "3.2"
actix-rt = "2.7"
actix-test = "0.1"
actix-web = "4.2"
#actix-web-actors = "4.1"
actix-ws = "0.2"
backtrace = "0.3"
base64 = "0.21"
bytes = "1.4"
bytestring = "1.2"
cadence = "0.29"
chrono = "0.4"
config = "0.13"
docopt = "1.1"
env_logger = "0.10"
fernet = "0.2.0"
# autoendpoint used futures 0.3
futures = {version="0.3", features=["compat"]}
futures-util = {version="0.3", features=["async-await", "compat", "sink", "io"]}
futures-locks = "0.7"
hex = "0.4.2"
httparse = "1.3"
hyper = "0.14"
lazy_static = "1.4"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
mozsvc-common = "0.2"
openssl = "0.10"
rand = "0.8"
regex = "1.4"
reqwest = {version="0.11", features = ["json"] }
rusoto_core = { version="0.47", default-features=false, features=["rustls"] } # locked by serde_dynamodb 0.9
rusoto_credential = { version="0.47"} # locked by serde_dynamodb 0.9
rusoto_dynamodb = { version="0.47", default-features=false, features=["rustls"]} # locked by serde_dynamodb 0.9
# Using debug-logs avoids https://github.com/getsentry/sentry-rust/issues/237
sentry = { version = "0.30", features = ["debug-logs"] }
sentry-core = {version = "0.30"}
sentry-actix = "0.30"
sentry-backtrace = "0.30"
serde = "1.0"
serde_derive = "1.0"
serde_dynamodb = "0.9"
serde_json = "1.0"
slog = { version = "2.7", features = ["dynamic-keys", "max_level_trace", "release_max_level_info"] }
slog-async = "2.6"
slog-envlogger = "2.2.0"
slog-mozlog-json = "0.1"
slog-scope = "4.4"
slog-stdlog = "4.1"
slog-term = "2.6"
thiserror = "1.0"
tokio = "1.26"
tokio-compat-02 = "0.2"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-openssl = "0.6"
tokio-tungstenite = { version = "0.9.0", default-features = false }  # 0.10+ requires tokio 0.3+
tungstenite = { version = "0.9.2", default-features = false }  # 0.10+ requires tokio 0.3+
uuid = { version = "1.1", features = ["serde", "v4"] }
url = "2.2"

autoconnect = { path = "./autoconnect" }
autoconnect_common = { path = "./autoconnect/autoconnect-common" }
autoconnect_settings = { path = "./autoconnect/autoconnect-settings" }
autoconnect_web = { path = "./autoconnect/autoconnect-web" }
autoconnect_ws = { path = "./autoconnect/autoconnect-ws" }
autoconnect_ws_clientsm = { path ="./autoconnect/autoconnect-ws/autoconnect-ws-clientsm" }
autopush_common = { path = "./autopush-common" }

[profile.release]
debug = 1
